Add vegnomes
vechain/app-hub pull request #126
Opened 2022-01-17 13:10 UTC by Bread-VeSea

Initial commit of VeGnomes NFT. Go live Saturday, 22nd

2022-01-18 05:18 UTC, XJWX89 requested changes
hi @Bread-VeSea , thanks for the submission ! currently the `manifest.json` on `main` branch ***does not*** contain `category ` & `contracts` fields. Moreover , please format the `manifest.json` before the submission.

2022-01-18 08:13 UTC, Bread-VeSea commented
@XJWX89 - manifest fixed. I was trying to future proof the content but got sloppy - sorry about that.

Also having to correct it via mobile and it's not playing nice, but think I have it. Let me know if there are any issues.

2022-01-18 08:17 UTC, AsbertMa commented on apps/io.vesea.vegnomes/manifest.json
> +# manifest.json
what's this？

2022-01-18 08:36 UTC, Bread-VeSea commented
@AsbertMa - text removed and shame added to family name.

2022-01-19 02:40 UTC, XJWX89 approved these changes

2022-01-20 06:36 UTC, merged