BVM Logo Update + Priority List
vechain/app-hub pull request #230
Opened 2023-06-26 16:30 UTC by Murtagh300

A small update on the Logo of BlackVeMarket, Aswell as the description.

Also a request to be on the promoted links on app hub.

2023-06-28 04:44 UTC, libotony requested changes

2023-06-28 04:44 UTC, libotony commented on scripts/promoted.ts
> +    'com.blackvemarket'
Kindly create a separate PR for this matter. We can discuss and address it there. We primarily consider the transaction volume, user count, and engagement level of the application.

2023-06-28 07:23 UTC, Murtagh300 commented
@libotony Fixxed

2023-06-29 02:56 UTC, libotony approved these changes

2023-06-29 02:57 UTC, merged